public class Constants {
    //Constants for workorder API integration
    public Static String POST = 'POST';
    public Static String status ='N';
    public Static String terminalCode ='PYM1';
	public Static String  pickUpNumber_Z ='0';
    public Static String  pickUpStopType ='PICKUP';
    public Static String  deliveryNumber_Z='1';
    public Static String deliveryStopType='DELIVERY';
    public Static String  contentType = 'Content-Type';
    public Static String  contentTypeValue ='application/json;charset=UTF-8';
    public Static String apiKey= 'ApiKey';
 
    //Constants for Opportunity Trigger and API integration
    Public Static String Authorization='Authorization';
    public Static String oppApiKeyValue ='API-Key 0277c350a54dede977e5fdca6a3e0fb1f362be31';
   
    
    
}